<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="uploadimage.aspx.cs" Inherits="Video.uploadimage" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>a page to upload image</title>
    <link rel="Stylesheet" type="text/css" href="style/jcrop_zn/css/jquery.Jcrop.css" />
    <script type="text/javascript" src="style/jquery-1.7.1.min.js"></script>
    <script type="text/javascript" src="style/jquery.filestyle.mini.js"></script>
    <script type="text/javascript" src="style/jquery.upload-1.0.2.min.js"></script>
    <script type="text/javascript" src="style/jcrop_zn/js/jquery.Jcrop.js"></script>
    <style type="text/css">
        html,body,dl,dd,h1,h2,h3,h4,h5,h6,p,form{margin:0;}
        fieldset,img{border:0;}
        body{width:640px;min-height:500px;}
        #contentTitle{display:none;}
        #siteTitle{margin-bottom:14px;font-size:18px;font-family:"Microsoft YaHei", "SimHei", serif;}
        h2{font-size:16px;font-weight:bold;border-bottom:1px solid #ccc;padding:1em 0 0.5em 0;margin:0 0 1em 0;color:#333;text-shadow:1px 1px #fff;}
        #tipsWraper{color:#666;margin:5px 5px 5px 0;font-size:12px;margin-bottom:1em;}
        #modify{display:none;}
        .button1 {-moz-box-shadow:inset 0px 1px 2px 0px #caefab;-webkit-box-shadow:inset 0px 1px 2px 0px #caefab;box-shadow:inset 0px 1px 2px 0px #caefab;background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #77d42a), color-stop(1, #5cb811) );background:-moz-linear-gradient( center top, #77d42a 5%, #5cb811 100% );filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#77d42a', endColorstr='#5cb811');background-color:#77d42a;-moz-border-radius:3px;-webkit-border-radius:3px;border-radius:3px;border:1px solid #268a16;display:inline-block;color:#306108;font-family:arial;font-size:12px;font-weight:bold;padding:6px 9px;text-decoration:none;text-shadow:1px 1px 0px #aade7c;}
        .button1:hover {background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #5cb811), color-stop(1, #77d42a) );background:-moz-linear-gradient( center top, #5cb811 5%, #77d42a 100% );filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#5cb811', endColorstr='#77d42a');background-color:#5cb811;}
        .button1:active {position:relative;top:1px;}
        .button2 {-moz-box-shadow:inset 0px 1px 2px 0px #caefab;-webkit-box-shadow:inset 0px 1px 2px 0px #caefab;box-shadow:inset 0px 1px 2px 0px #caefab;background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #77d42a), color-stop(1, #5cb811) );background:-moz-linear-gradient( center top, #77d42a 5%, #5cb811 100% );filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#77d42a', endColorstr='#5cb811');background-color:#77d42a;-moz-border-radius:3px;-webkit-border-radius:3px;border-radius:3px;border:1px solid #268a16;display:inline-block;color:#306108;font-family:arial;font-size:12px;font-weight:bold;padding:6px 9px;text-decoration:none;text-shadow:1px 1px 0px #aade7c;}
        .button2:hover {background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #5cb811), color-stop(1, #77d42a) );background:-moz-linear-gradient( center top, #5cb811 5%, #77d42a 100% );filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#5cb811', endColorstr='#77d42a');background-color:#5cb811;}
        .button2:active {position:relative;top:1px;}
        /* This imageless css button was generated by CSSButtonGenerator.com */
    </style>
    <script type="text/javascript">
        function showCoords(obj) {
            $('#hiddenSelectHW').val(obj.x + "," + obj.y + "," + obj.w + "," + obj.h);
        }

        $(document).ready(function() {
            //loadImage
            $("#imageUploader").filestyle({ image: "style/uploadImage1.png", imageheight: 31, imagewidth: 71, width: 306 });
            $("#imageUploader").parent().css('cursor', 'pointer');
            $("#imageUploader").parent().css('background', 'url(style/uploadImage1.png) no-repeat 0 0');
            $("#imageUploader").parent().hover(
                function() {
                    $(this).css('background', 'url(style/uploadImage2.png) no-repeat 0 0');
                },
                function() {
                    $(this).css('background', 'url(style/uploadImage1.png) no-repeat 0 0');
                }
            );
            $("#imageUploader").parent().prev().css({
                'font-size': '14px',
                'line-height': '26px',
                'color': '#666',
                'border': '0 none',
                'width': '220px',
                'height': '31px',
                'padding': '0 0 0 10px',
                'margin': '0 5px 0 0',
                'background': 'url(style/uploadImage.png) no-repeat 0 0'
            });
            //modify image
            $("#imageToModify").Jcrop({
                onSelect: showCoords
            });
        });
    </script>
</head>
<body>
    <form id="form1" runat="server">
    <div id="wraper">
        <h1 runat="server" id="contentTitle"></h1>
        <h1 runat="server" id="siteTitle"></h1>
        
        <h2>1.上传图片</h2>
        <div id="upload">
            <div>
                <asp:FileUpload runat="server" ID="imageUploader" />
            </div>
            <div id="tipsWraper">
                <asp:Label runat="server" ID="uploadInfo">Tips:上传图片的格式为jpg,jepg,bmp,小于1M</asp:Label>
            </div>
            <div>
                <asp:LinkButton runat="server" ID="imageUploadButton"  OnClick="imageUpload_tj" CssClass="button1">开始上传</asp:LinkButton>
            </div>
        </div>
        
        <h2>2.选择区域</h2>
        <div id="modify" runat="server">
            <asp:Image runat="server" ID="imageToModify" />
            <asp:HiddenField runat="server" ID="hiddenHW" Value="0,0" />
            <asp:HiddenField runat="server" ID="hiddenSelectHW" Value="0,0,0,0" />
            <asp:HiddenField runat="server" ID="hiddenFileName" Value="" />
        </div>
        
        <h2>3.确定提交</h2>
        <div id="submitSelect">
            <asp:LinkButton runat="server" ID="imageSelectArea" OnClick="imageSelectArea_tj" CssClass="button2">确定提交</asp:LinkButton>
        </div>
    </div>
    </form>
</body>
</html>
